set nocompatible

set backupdir=$XDG_CACHE_HOME/vim,/var/tmp,/tmp
set directory=$XDG_CACHE_HOME/vim,/var/tmp,/tmp
set viminfo+=n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
