#!/usr/bin/env zsh

# Set core environment variables.
export XDG_BIN_HOME="${HOME}/.local/bin"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_LIB_HOME="${HOME}/.local/lib"
export ZDOTDIR="${XDG_DATA_HOME}/zsh"

# Source Zsh configuration files.
for _dir in "${XDG_CONFIG_HOME}/zsh/zshenv.d/"{before,.,after}; do
    if test -d "$_dir"; then
        for _file in "${_dir}/"*".zsh"; do
            test -r "$_file" && source "$_file"
        done
    fi
done

# Remove unneeded variables.
unset _dir
unset _file
