#!/usr/bin/env zsh

# Source Zsh configuration files.
for _dir in "${XDG_CONFIG_HOME}/zsh/zshrc.d/"{before,.,after}; do
    if test -d "$_dir"; then
        for _file in "${_dir}/"*".zsh"; do
            test -r "$_file" && source "$_file"
        done
    fi
done

# Remove unneeded variables.
unset _dir
unset _file
